Version 1.1

diff --git a/SIESTA-Band-gap-Calculation/calc_gap b/SIESTA-Band-gap-Calculation/calc_gap
--- a/SIESTA-Band-gap-Calculation/calc_gap
+++ b/SIESTA-Band-gap-Calculation/calc_gap
@@ -1,20 +1,12 @@
 #!/bin/bash
 
-#WHAT DOES THIS SCRIPT DO? It calculates the band-gap energy through the .bands file. If you have many .bands file in a folder, it will calculates the band-gap energy for ALL the .bands file.
+#WHAT DOES THIS SCRIPT DO? 
+#It calculates the band-gap energy through the .bands file. If you have many .bands file in a folder, it will calculates the band-gap energy for ALL the .bands file.
 
 #HOW TO USE?
 #Copy this script to your calculation folder that contains the .bands file. Or copy all of your .bands file to the same folder and put this script there.
 #Type in the therminal the following command: ./calc_gap
 #If you get error, type in the terminal: chmod +x calc_gap
-
-echo "Do you want verify if the band-gap is direct or indirect (EXPERIMENTAL)? (Y)Yes (N)No"
-read awn1
-if [ $awn1 == "Y" ] || [ $awn1 == "y" ]
-then
-	mostrar_tipo_de_gap=1
-else
-	mostrar_tipo_de_gap=0
-fi
 
 #Adjust this variable to modify the way this script checks whether the gap is direct or indirect. In general, the band is plotted between the values of 0.00 and 0.12 eV for the X axis, so to check if the top of the valence band is aligned with the bottom of the conduction band within a certain limit, it is Once a tolerance is established, the smaller the tolerance, the small variations in the X-axis values for the top of the valence and the bottom of the conduction will answer that the gap is Indirect, and vice versa.
 tolerancia=0.003
@@ -24,9 +16,60 @@ variation=0.01
 
 #By: Caio Vinícius C. R. da Silva - caioviniciuscaetano@hotmail.com
 
+helpFunction()
+{
+   echo -e "WHAT DOES THIS TOOL DO?\nIt calculates the band-gap energy through the .bands file. If you have many .bands file in a folder, it will calculates the band-gap energy for ALL the .bands file."
+   echo -e "\nUSAGE:\nCopy this script to your calculation folder that contains the .bands file. Or copy all of your .bands file to the same folder and put this script there.\nType in the therminal the following command: ./calc_gap\nIf you get error, type in the terminal: chmod +x calc_gap"
+   echo -e "\nOPTIONS:\n-s or --show: Show if the band-gap is DIRECT or INDIRECT. However, this is an EXPERIMENTAL option, so sometimes the answer shown may be wrong.\n-x or --x_variation: Default: 0.003. Use this to improve the precision of prediction if the gap is DIRECT or INDIRECT. It will modify the variation of X axis values used to verify the band-gap type.\n-y or --y_variation: Default: 0.01. Use this to improve the precision of prediction if the gap is DIRECT or INDIRECT. It will modify the variation of Y axis values used to verify the band-gap type.\n-h or --help: Show the help.\n-V or --Version: Show the help"
+   exit 1 # Exit script after printing help
+}
+mostrar_tipo_de_gap=0
+for arg in "$@"
+do
+    case $arg in
+	-s | --show )
+	mostrar_tipo_de_gap=1
+	shift
+	;;
+	
+	-x | --x_variation )
+	tolerancia=$2
+	len=${#tolerancia}
+	testvar=$(echo "$tolerancia" | tr -c '0-9.' '\n')     # remove non-numeric chars from $tolerancia
+	if [[ $len -ne ${#testvar} ]] ; then 
+		echo -e "\nError: $tolerancia is not a number"  # error message
+		exit
+	fi
+	shift
+	shift
+	;;
+	
+	-y | --y_variation )
+	variation=$2
+	len=${#variation}
+	testvar=$(echo "$variation" | tr -c '0-9.' '\n')     # remove non-numeric chars from $variation
+	if [[ $len -ne ${#testvar} ]] ; then 
+		echo -e "\nError: $variation is not a number"  # error message
+		exit
+	fi
+	shift
+	shift
+	;;
+	
+    -V | --Version )
+      echo 1.1
+	  exit
+    ;;
+	
+	-h | --help )
+	helpFunction 
+	;;  
+  esac
+done
+
 bands=(`find *.bands`)
 if [ ${#bands[*]} -eq 0 ];then
-  echo -e "\nERRO: No .bands file found"
+  echo -e "\nERROR: No .bands file found"
   exit  
 fi 
 
